ALTER TABLE members ADD COLUMN street TEXT;
ALTER TABLE members ADD COLUMN zip TEXT;
ALTER TABLE members ADD COLUMN city TEXT;
ALTER TABLE members ADD COLUMN join_date DATE;
ALTER TABLE members ADD COLUMN iban TEXT;
ALTER TABLE members ADD COLUMN photo_path TEXT;
ALTER TABLE members ADD COLUMN photo_visible INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN dsgvo_verarbeitung INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN dsgvo_verarbeitung_date DATE;
ALTER TABLE members ADD COLUMN dsgvo_weitergabe INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN dsgvo_weitergabe_date DATE;
ALTER TABLE members ADD COLUMN sepa_mandat INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN sepa_mandat_date DATE;
ALTER TABLE members ADD COLUMN sepa_mandat_path TEXT;
