ALTER TABLE members ADD COLUMN phones_visible INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN address_visible INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN email_visible INTEGER NOT NULL DEFAULT 0;

CREATE TABLE member_phones (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  label TEXT NOT NULL DEFAULT '',
  number TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);
